spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      "[format_sql]": true

cors:
  allowed:
    origins:
      - ${CORS_ALLOWED_ORINGS}
    methods:
      - GET
      - POST
      - PUT
    headers:
      - '*'

public:
  data:
    weather: ${PUBLIC_DATA_API_KEY}