spring:
  application:
    name: HomeMonitor
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: INFO
            extract: INFO

public:
  data:
    weather: ${PUBLIC_DATA_API_KEY}

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}