spring:
  application:
    name: HomeMonitor
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
        

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: INFO
            extract: INFO

public:
  data:
    weather: ${PUBLIC_DATA_API_KEY}

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

host: ${HOST}

image:
  upload_dir: ${IMAGE_UPLOAD_DIR}
  url_prefix: ${IMAGE_URL_PREFIX}