spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      "[format_sql]": true

logging:
  level:
    root: INFO

cors:
  allowed:
    origins:
      - ${CORS_ALLOWED_ORIGINS}
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    headers:
      - '*'

jwt:
  secret: ${JWT_SECRET}
  expire_time: 86400000

springdoc:
  api-docs:
    enabled: false