spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      "[format_sql]": true
      
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

cors:
  allowed:
    origins:
      - http://localhost:5173
    methods:
      - GET
    headers:
      - '*'